services:
  postgres:
    image: postgres:16-alpine
    container_name: ergon-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: ergon
      POSTGRES_PASSWORD: ergon123
      POSTGRES_DB: ergon_foundation
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
